apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
  namespace: mrjamiebowman
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ValuesConfiguration": {
        "Message": "The configuration is working!" 
      } 
    }